- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
     msg: " Hello {{course | default('Ansible')}}"


- name: upper case
  hosts: localhost
  vars:
   greeting: "Hello,Good morning"
  tasks: 
  - name: convert into upper case
    ansible.builtin.debug:
     msg: "{{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "HELLO GOOD MORNING"
  tasks:
   - name: convert into lower case
     ansible.builtin.debug:
      msg: "{{ greeting | lower }}"
  
- name: remove duplicates
  hosts: localhost
  vars:
   numbers: [1,2,3,6,9,8,8,6,5,3]
  tasks:
   - name: remove duplicate numbers
     ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  
- name : mimimum and maximum
  hosts: localhost
  vars:
     ages: [25,46,67, 89]
  tasks:
    - name: print minimun and maximum age
      ansible.builtin.debug:
       msg: " min age: {{ ages | min }}, maximum age: {{ ages | max }}"

# dictionary=map=key,value
- name:  convert dictionary into list
  hosts: localhost
  vars:
    dict:
     Course: Devops with AWS
     Trainer: Siva
     Duration: "120hrs"
  tasks:
   - name: converting dictionary into list
     ansible.builtin.debug:
      msg: " {{ dict | dict2items }}"

## convert list into dictionary
- name: convert list into dictionary
  hosts: localhost
  vars:
    list: [{'key': 'Course', 'value': 'Devops with AWS'}, {'key': 'Trainer', 'value': 'Siva'}, {'key': 'Duration', 'value': '120hrs'}]
  tasks:
   - name: convert list into dictionary
     ansible.builtin.debug:
       msg: "{{ list | items2dict }}"