- name: install packages
  hosts: web
  become: true
  tasks:
   - name: install packages
     ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest 
     loop:
      - git
      - nginx
      - postfix