- name: command vs shell
  hosts: localhost
  tasks:
   - name: command module
     ansible.buitlin.command: "echo 'Hi, this is from command module' > /tmp/command.txt "

   - name: shell module
     ansible.buitlin.shell: "echo 'Hi, this is from shell module' > /tmp/shell.txt "