- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    ansible.buitlin.bebug:
     msg: "Hi,We are learning {{Course}}, from Trainer {{Trainer}},Duration is {{Duration}}"